/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include <falso_jni/FalsoJNI_Logger.h>
#include "generated_jni_table.h"

// ---- com.gameloft.android.GAND.GloftA5HD.Asphalt5 ----
jboolean stub_Asphalt5_isWifiActive_0(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.isWifiActive()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_Asphalt5_onCreate_1(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jint stub_Asphalt5_getLanguage_2(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.getLanguage(Ljava/lang/String;Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    return 0;
}

void stub_Asphalt5_onPause_3(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_SetLoadingValuable_4(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.SetLoadingValuable(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Asphalt5_onResume_5(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_onStop_6(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_onDestroy_7(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_onRestart_8(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_onStart_9(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onStart()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Asphalt5_onTrackballEvent_10(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onTrackballEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Asphalt5_onKeyDown_11(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Asphalt5_onKeyUp_12(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_Asphalt5_onTouchEvent_13(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_Asphalt5_loadMovie_14(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.loadMovie(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_Asphalt5_onSensorChanged_15(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onSensorChanged(LSensorEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Asphalt5_onAccuracyChanged_16(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onAccuracyChanged(LSensor;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

void stub_Asphalt5_sendAppToBackground_17(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.sendAppToBackground()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_Exit_18(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.Exit()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_LaunchBilling_19(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.LaunchBilling()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_ReleaseBillingContext_20(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.ReleaseBillingContext()V called -- fill in from the real Java impl (jadx).");
}

jint stub_Asphalt5_IsDemo_21(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.IsDemo()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_Asphalt5_IsDoubleOption_22(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.IsDoubleOption()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_Asphalt5_GetDoubleOptionText1_23(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.GetDoubleOptionText1()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Asphalt5_GetDoubleOptionText2_24(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.GetDoubleOptionText2()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Asphalt5_GetDoubleOptionText3_25(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.GetDoubleOptionText3()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Asphalt5_onActivityResult_26(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Asphalt5_launchGetGames_27(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.launchGetGames(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Asphalt5_OpenGLive_28(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.OpenGLive(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Asphalt5_NotifyTrophy_29(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.NotifyTrophy(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Asphalt5_readFromFile_30(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.readFromFile()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5_initialize_Trophy_31(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5.initialize_Trophy([I)V called -- fill in from the real Java impl (jadx).");
    jintArray arg0 = (jintArray) va_arg(args, jobject);
}

// ---- com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView ----
jobject stub_Asphalt5GLSurfaceView_Asphalt5GLSurfaceView_32(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView.Asphalt5GLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_Asphalt5GLSurfaceView_onWindowFocusChanged_33(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_Asphalt5GLSurfaceView_onSizeChanged_34(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView.onSizeChanged(IIII)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

void stub_Asphalt5GLSurfaceView_onResume_35(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_Asphalt5GLSurfaceView_onPause_36(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView.onPause()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer ----
jobject stub_Asphalt5Renderer_Asphalt5Renderer_37(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer.Asphalt5Renderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_Asphalt5Renderer_onSurfaceCreated_38(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Asphalt5Renderer_onSurfaceChanged_39(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_Asphalt5Renderer_surfaceDestroyed_40(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer.surfaceDestroyed(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Asphalt5Renderer_onDrawFrame_41(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer ----
void stub_GLMediaPlayer_init_42(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.init()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_init_43(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.init(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

jint stub_GLMediaPlayer_isSoundLoaded_44(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.isSoundLoaded(II)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_isSoundLoadedBig_45(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.isSoundLoadedBig(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLMediaPlayer_loadSound_46(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.loadSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_loadSound_47(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.loadSound(IILContext;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GLMediaPlayer_loadSoundBig_48(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.loadSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_loadSoundBig_49(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.loadSoundBig(ILContext;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GLMediaPlayer_playSound_50(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.playSound(IIF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jfloat arg2 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_playSoundBig_51(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.playSoundBig(IF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_setLoopBig_52(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.setLoopBig(IZ)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jboolean arg1 = (jboolean) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseSound_53(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.pauseSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseSoundBig_54(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.pauseSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeSound_55(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.resumeSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeSoundBig_56(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.resumeSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSound_57(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.stopSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSoundBig_58(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.stopSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadSound_59(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.unloadSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadSoundBig_60(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.unloadSoundBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_setVolume_61(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.setVolume(IIF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jfloat arg2 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_setVolumeBig_62(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.setVolumeBig(IF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_resetSound_63(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.resetSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_setPitch_64(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.setPitch(IIF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jfloat arg2 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_stopAllSounds_65(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.stopAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_stopAllPool_66(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.stopAllPool(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopAllBig_67(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.stopAllBig(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_destroySoundPool_68(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.destroySoundPool()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_loadMovie_69(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.loadMovie(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_ResumeMovie_70(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.ResumeMovie()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GLMediaPlayer_isMediaPlaying_71(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.isMediaPlaying(I)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return JNI_FALSE;
}

void stub_GLMediaPlayer_releaseSoundPool_72(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.releaseSoundPool()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_initSoundPoolArray_73(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer.initSoundPoolArray()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.GAND.GloftA5HD.GLResLoader ----
void stub_GLResLoader_init_74(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.init()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GLResLoader_getResourceLength_75(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.getResourceLength(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jbyteArray stub_GLResLoader_getResourceFull_76(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.getResourceFull(Ljava/lang/String;)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceFull_77(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.getResourceFull(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_GLResLoader_getRawResource_78(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.getRawResource(ILContext;)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceBytes_79(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.getResourceBytes(Ljava/lang/String;II)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    return NULL;
}

jobject stub_GLResLoader_getString_80(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.GLResLoader.getString(ILContext;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

// ---- com.gameloft.android.GAND.GloftA5HD.IGPActivity ----
void stub_IGPActivity_onCreate_81(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IGPActivity_onPause_82(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_onResume_83(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_onRestart_84(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_onStart_85(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_onStop_86(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_openBrowser_87(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.openBrowser(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IGPActivity_sendAppToBackground_88(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.sendAppToBackground()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_Exit_89(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.Exit()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPActivity_BackToMainActivity_90(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.BackToMainActivity()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_IGPActivity_onKeyDown_91(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_IGPActivity_onKeyUp_92(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_IGPActivity_onTouchEvent_93(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPActivity.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

// ---- com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView ----
jobject stub_IGPGLSurfaceView_IGPGLSurfaceView_94(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView.IGPGLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_IGPGLSurfaceView_onWindowFocusChanged_95(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_IGPGLSurfaceView_onSizeChanged_96(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView.onSizeChanged(IIII)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

// ---- com.gameloft.android.GAND.GloftA5HD.IGPRenderer ----
jobject stub_IGPRenderer_IGPRenderer_97(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPRenderer.IGPRenderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_IGPRenderer_onSurfaceCreated_98(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IGPRenderer_onSurfaceChanged_99(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_IGPRenderer_onDrawFrame_100(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jint stub_IGPRenderer_isMotoPhone_101(jmethodID id, va_list args) {
    fjni_log_dbg("[JNI STUB] com.gameloft.android.GAND.GloftA5HD.IGPRenderer.isMotoPhone()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

