/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jboolean stub_Asphalt5_isWifiActive_0(jmethodID id, va_list args);
extern void stub_Asphalt5_onCreate_1(jmethodID id, va_list args);
extern jint stub_Asphalt5_getLanguage_2(jmethodID id, va_list args);
extern void stub_Asphalt5_onPause_3(jmethodID id, va_list args);
extern void stub_Asphalt5_SetLoadingValuable_4(jmethodID id, va_list args);
extern void stub_Asphalt5_onResume_5(jmethodID id, va_list args);
extern void stub_Asphalt5_onStop_6(jmethodID id, va_list args);
extern void stub_Asphalt5_onDestroy_7(jmethodID id, va_list args);
extern void stub_Asphalt5_onRestart_8(jmethodID id, va_list args);
extern void stub_Asphalt5_onStart_9(jmethodID id, va_list args);
extern jboolean stub_Asphalt5_onTrackballEvent_10(jmethodID id, va_list args);
extern jboolean stub_Asphalt5_onKeyDown_11(jmethodID id, va_list args);
extern jboolean stub_Asphalt5_onKeyUp_12(jmethodID id, va_list args);
extern jboolean stub_Asphalt5_onTouchEvent_13(jmethodID id, va_list args);
extern void stub_Asphalt5_loadMovie_14(jmethodID id, va_list args);
extern void stub_Asphalt5_onSensorChanged_15(jmethodID id, va_list args);
extern void stub_Asphalt5_onAccuracyChanged_16(jmethodID id, va_list args);
extern void stub_Asphalt5_sendAppToBackground_17(jmethodID id, va_list args);
extern void stub_Asphalt5_Exit_18(jmethodID id, va_list args);
extern void stub_Asphalt5_LaunchBilling_19(jmethodID id, va_list args);
extern void stub_Asphalt5_ReleaseBillingContext_20(jmethodID id, va_list args);
extern jint stub_Asphalt5_IsDemo_21(jmethodID id, va_list args);
extern jint stub_Asphalt5_IsDoubleOption_22(jmethodID id, va_list args);
extern jobject stub_Asphalt5_GetDoubleOptionText1_23(jmethodID id, va_list args);
extern jobject stub_Asphalt5_GetDoubleOptionText2_24(jmethodID id, va_list args);
extern jobject stub_Asphalt5_GetDoubleOptionText3_25(jmethodID id, va_list args);
extern void stub_Asphalt5_onActivityResult_26(jmethodID id, va_list args);
extern void stub_Asphalt5_launchGetGames_27(jmethodID id, va_list args);
extern void stub_Asphalt5_OpenGLive_28(jmethodID id, va_list args);
extern void stub_Asphalt5_NotifyTrophy_29(jmethodID id, va_list args);
extern void stub_Asphalt5_readFromFile_30(jmethodID id, va_list args);
extern void stub_Asphalt5_initialize_Trophy_31(jmethodID id, va_list args);
extern jobject stub_Asphalt5GLSurfaceView_Asphalt5GLSurfaceView_32(jmethodID id, va_list args);
extern void stub_Asphalt5GLSurfaceView_onWindowFocusChanged_33(jmethodID id, va_list args);
extern void stub_Asphalt5GLSurfaceView_onSizeChanged_34(jmethodID id, va_list args);
extern void stub_Asphalt5GLSurfaceView_onResume_35(jmethodID id, va_list args);
extern void stub_Asphalt5GLSurfaceView_onPause_36(jmethodID id, va_list args);
extern jobject stub_Asphalt5Renderer_Asphalt5Renderer_37(jmethodID id, va_list args);
extern void stub_Asphalt5Renderer_onSurfaceCreated_38(jmethodID id, va_list args);
extern void stub_Asphalt5Renderer_onSurfaceChanged_39(jmethodID id, va_list args);
extern void stub_Asphalt5Renderer_surfaceDestroyed_40(jmethodID id, va_list args);
extern void stub_Asphalt5Renderer_onDrawFrame_41(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_init_42(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_init_43(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isSoundLoaded_44(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isSoundLoadedBig_45(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSound_46(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSound_47(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSoundBig_48(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSoundBig_49(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playSound_50(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playSoundBig_51(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setLoopBig_52(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseSound_53(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseSoundBig_54(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeSound_55(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeSoundBig_56(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSound_57(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSoundBig_58(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadSound_59(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadSoundBig_60(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVolume_61(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVolumeBig_62(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resetSound_63(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setPitch_64(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllSounds_65(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllPool_66(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllBig_67(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_destroySoundPool_68(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadMovie_69(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_ResumeMovie_70(jmethodID id, va_list args);
extern jboolean stub_GLMediaPlayer_isMediaPlaying_71(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_releaseSoundPool_72(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_initSoundPoolArray_73(jmethodID id, va_list args);
extern void stub_GLResLoader_init_74(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceLength_75(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_76(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_77(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getRawResource_78(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceBytes_79(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getString_80(jmethodID id, va_list args);
extern void stub_IGPActivity_onCreate_81(jmethodID id, va_list args);
extern void stub_IGPActivity_onPause_82(jmethodID id, va_list args);
extern void stub_IGPActivity_onResume_83(jmethodID id, va_list args);
extern void stub_IGPActivity_onRestart_84(jmethodID id, va_list args);
extern void stub_IGPActivity_onStart_85(jmethodID id, va_list args);
extern void stub_IGPActivity_onStop_86(jmethodID id, va_list args);
extern void stub_IGPActivity_openBrowser_87(jmethodID id, va_list args);
extern void stub_IGPActivity_sendAppToBackground_88(jmethodID id, va_list args);
extern void stub_IGPActivity_Exit_89(jmethodID id, va_list args);
extern void stub_IGPActivity_BackToMainActivity_90(jmethodID id, va_list args);
extern jboolean stub_IGPActivity_onKeyDown_91(jmethodID id, va_list args);
extern jboolean stub_IGPActivity_onKeyUp_92(jmethodID id, va_list args);
extern jboolean stub_IGPActivity_onTouchEvent_93(jmethodID id, va_list args);
extern jobject stub_IGPGLSurfaceView_IGPGLSurfaceView_94(jmethodID id, va_list args);
extern void stub_IGPGLSurfaceView_onWindowFocusChanged_95(jmethodID id, va_list args);
extern void stub_IGPGLSurfaceView_onSizeChanged_96(jmethodID id, va_list args);
extern jobject stub_IGPRenderer_IGPRenderer_97(jmethodID id, va_list args);
extern void stub_IGPRenderer_onSurfaceCreated_98(jmethodID id, va_list args);
extern void stub_IGPRenderer_onSurfaceChanged_99(jmethodID id, va_list args);
extern void stub_IGPRenderer_onDrawFrame_100(jmethodID id, va_list args);
extern jint stub_IGPRenderer_isMotoPhone_101(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "isWifiActive", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 1, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 2, "getLanguage", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 3, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 4, "SetLoadingValuable", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 5, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 6, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 7, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 8, "onRestart", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 9, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 10, "onTrackballEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 11, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 12, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 13, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 14, "loadMovie", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 15, "onSensorChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 16, "onAccuracyChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 17, "sendAppToBackground", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 18, "Exit", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 19, "LaunchBilling", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 20, "ReleaseBillingContext", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 21, "IsDemo", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 22, "IsDoubleOption", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 23, "GetDoubleOptionText1", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 24, "GetDoubleOptionText2", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 25, "GetDoubleOptionText3", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 26, "onActivityResult", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 27, "launchGetGames", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 28, "OpenGLive", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 29, "NotifyTrophy", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 30, "readFromFile", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 31, "initialize_Trophy", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5
    { 32, "Asphalt5GLSurfaceView", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView
    { 33, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView
    { 34, "onSizeChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView
    { 35, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView
    { 36, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5GLSurfaceView
    { 37, "Asphalt5Renderer", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer
    { 38, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer
    { 39, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer
    { 40, "surfaceDestroyed", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer
    { 41, "onDrawFrame", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.Asphalt5Renderer
    { 42, "init", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 43, "init", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 44, "isSoundLoaded", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 45, "isSoundLoadedBig", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 46, "loadSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 47, "loadSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 48, "loadSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 49, "loadSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 50, "playSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 51, "playSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 52, "setLoopBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 53, "pauseSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 54, "pauseSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 55, "resumeSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 56, "resumeSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 57, "stopSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 58, "stopSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 59, "unloadSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 60, "unloadSoundBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 61, "setVolume", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 62, "setVolumeBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 63, "resetSound", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 64, "setPitch", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 65, "stopAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 66, "stopAllPool", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 67, "stopAllBig", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 68, "destroySoundPool", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 69, "loadMovie", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 70, "ResumeMovie", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 71, "isMediaPlaying", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 72, "releaseSoundPool", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 73, "initSoundPoolArray", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLMediaPlayer
    { 74, "init", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 75, "getResourceLength", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 76, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 77, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 78, "getRawResource", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 79, "getResourceBytes", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 80, "getString", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.GLResLoader
    { 81, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 82, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 83, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 84, "onRestart", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 85, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 86, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 87, "openBrowser", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 88, "sendAppToBackground", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 89, "Exit", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 90, "BackToMainActivity", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 91, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 92, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 93, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.GAND.GloftA5HD.IGPActivity
    { 94, "IGPGLSurfaceView", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView
    { 95, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView
    { 96, "onSizeChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPGLSurfaceView
    { 97, "IGPRenderer", METHOD_TYPE_OBJECT },  // com.gameloft.android.GAND.GloftA5HD.IGPRenderer
    { 98, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPRenderer
    { 99, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPRenderer
    { 100, "onDrawFrame", METHOD_TYPE_VOID },  // com.gameloft.android.GAND.GloftA5HD.IGPRenderer
    { 101, "isMotoPhone", METHOD_TYPE_INT },  // com.gameloft.android.GAND.GloftA5HD.IGPRenderer
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 0, stub_Asphalt5_isWifiActive_0 },
    { 10, stub_Asphalt5_onTrackballEvent_10 },
    { 11, stub_Asphalt5_onKeyDown_11 },
    { 12, stub_Asphalt5_onKeyUp_12 },
    { 13, stub_Asphalt5_onTouchEvent_13 },
    { 71, stub_GLMediaPlayer_isMediaPlaying_71 },
    { 91, stub_IGPActivity_onKeyDown_91 },
    { 92, stub_IGPActivity_onKeyUp_92 },
    { 93, stub_IGPActivity_onTouchEvent_93 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 1, stub_Asphalt5_onCreate_1 },
    { 3, stub_Asphalt5_onPause_3 },
    { 4, stub_Asphalt5_SetLoadingValuable_4 },
    { 5, stub_Asphalt5_onResume_5 },
    { 6, stub_Asphalt5_onStop_6 },
    { 7, stub_Asphalt5_onDestroy_7 },
    { 8, stub_Asphalt5_onRestart_8 },
    { 9, stub_Asphalt5_onStart_9 },
    { 14, stub_Asphalt5_loadMovie_14 },
    { 15, stub_Asphalt5_onSensorChanged_15 },
    { 16, stub_Asphalt5_onAccuracyChanged_16 },
    { 17, stub_Asphalt5_sendAppToBackground_17 },
    { 18, stub_Asphalt5_Exit_18 },
    { 19, stub_Asphalt5_LaunchBilling_19 },
    { 20, stub_Asphalt5_ReleaseBillingContext_20 },
    { 26, stub_Asphalt5_onActivityResult_26 },
    { 27, stub_Asphalt5_launchGetGames_27 },
    { 28, stub_Asphalt5_OpenGLive_28 },
    { 29, stub_Asphalt5_NotifyTrophy_29 },
    { 30, stub_Asphalt5_readFromFile_30 },
    { 31, stub_Asphalt5_initialize_Trophy_31 },
    { 33, stub_Asphalt5GLSurfaceView_onWindowFocusChanged_33 },
    { 34, stub_Asphalt5GLSurfaceView_onSizeChanged_34 },
    { 35, stub_Asphalt5GLSurfaceView_onResume_35 },
    { 36, stub_Asphalt5GLSurfaceView_onPause_36 },
    { 38, stub_Asphalt5Renderer_onSurfaceCreated_38 },
    { 39, stub_Asphalt5Renderer_onSurfaceChanged_39 },
    { 40, stub_Asphalt5Renderer_surfaceDestroyed_40 },
    { 41, stub_Asphalt5Renderer_onDrawFrame_41 },
    { 42, stub_GLMediaPlayer_init_42 },
    { 43, stub_GLMediaPlayer_init_43 },
    { 46, stub_GLMediaPlayer_loadSound_46 },
    { 47, stub_GLMediaPlayer_loadSound_47 },
    { 48, stub_GLMediaPlayer_loadSoundBig_48 },
    { 49, stub_GLMediaPlayer_loadSoundBig_49 },
    { 50, stub_GLMediaPlayer_playSound_50 },
    { 51, stub_GLMediaPlayer_playSoundBig_51 },
    { 52, stub_GLMediaPlayer_setLoopBig_52 },
    { 53, stub_GLMediaPlayer_pauseSound_53 },
    { 54, stub_GLMediaPlayer_pauseSoundBig_54 },
    { 55, stub_GLMediaPlayer_resumeSound_55 },
    { 56, stub_GLMediaPlayer_resumeSoundBig_56 },
    { 57, stub_GLMediaPlayer_stopSound_57 },
    { 58, stub_GLMediaPlayer_stopSoundBig_58 },
    { 59, stub_GLMediaPlayer_unloadSound_59 },
    { 60, stub_GLMediaPlayer_unloadSoundBig_60 },
    { 61, stub_GLMediaPlayer_setVolume_61 },
    { 62, stub_GLMediaPlayer_setVolumeBig_62 },
    { 63, stub_GLMediaPlayer_resetSound_63 },
    { 64, stub_GLMediaPlayer_setPitch_64 },
    { 65, stub_GLMediaPlayer_stopAllSounds_65 },
    { 66, stub_GLMediaPlayer_stopAllPool_66 },
    { 67, stub_GLMediaPlayer_stopAllBig_67 },
    { 68, stub_GLMediaPlayer_destroySoundPool_68 },
    { 69, stub_GLMediaPlayer_loadMovie_69 },
    { 70, stub_GLMediaPlayer_ResumeMovie_70 },
    { 72, stub_GLMediaPlayer_releaseSoundPool_72 },
    { 73, stub_GLMediaPlayer_initSoundPoolArray_73 },
    { 74, stub_GLResLoader_init_74 },
    { 81, stub_IGPActivity_onCreate_81 },
    { 82, stub_IGPActivity_onPause_82 },
    { 83, stub_IGPActivity_onResume_83 },
    { 84, stub_IGPActivity_onRestart_84 },
    { 85, stub_IGPActivity_onStart_85 },
    { 86, stub_IGPActivity_onStop_86 },
    { 87, stub_IGPActivity_openBrowser_87 },
    { 88, stub_IGPActivity_sendAppToBackground_88 },
    { 89, stub_IGPActivity_Exit_89 },
    { 90, stub_IGPActivity_BackToMainActivity_90 },
    { 95, stub_IGPGLSurfaceView_onWindowFocusChanged_95 },
    { 96, stub_IGPGLSurfaceView_onSizeChanged_96 },
    { 98, stub_IGPRenderer_onSurfaceCreated_98 },
    { 99, stub_IGPRenderer_onSurfaceChanged_99 },
    { 100, stub_IGPRenderer_onDrawFrame_100 },
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 2, stub_Asphalt5_getLanguage_2 },
    { 21, stub_Asphalt5_IsDemo_21 },
    { 22, stub_Asphalt5_IsDoubleOption_22 },
    { 44, stub_GLMediaPlayer_isSoundLoaded_44 },
    { 45, stub_GLMediaPlayer_isSoundLoadedBig_45 },
    { 75, stub_GLResLoader_getResourceLength_75 },
    { 101, stub_IGPRenderer_isMotoPhone_101 },
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 23, stub_Asphalt5_GetDoubleOptionText1_23 },
    { 24, stub_Asphalt5_GetDoubleOptionText2_24 },
    { 25, stub_Asphalt5_GetDoubleOptionText3_25 },
    { 32, stub_Asphalt5GLSurfaceView_Asphalt5GLSurfaceView_32 },
    { 37, stub_Asphalt5Renderer_Asphalt5Renderer_37 },
    { 76, stub_GLResLoader_getResourceFull_76 },
    { 77, stub_GLResLoader_getResourceFull_77 },
    { 78, stub_GLResLoader_getRawResource_78 },
    { 79, stub_GLResLoader_getResourceBytes_79 },
    { 80, stub_GLResLoader_getString_80 },
    { 94, stub_IGPGLSurfaceView_IGPGLSurfaceView_94 },
    { 97, stub_IGPRenderer_IGPRenderer_97 },
};

