/* Auto-generated by psvita-toolkit -- instrumented heap allocator wrappers. */
/* This toolkit has no ELF loader/relocator of its own, so it can't hook the  */
/* game .so's malloc/free calls automatically (same limitation documented in  */
/* so_patcher.py). Register mp_malloc/mp_calloc/mp_realloc/mp_free below in    */
/* place of the real malloc/calloc/realloc/free entries in your soloader's own */
/* libc import-resolution table. See docs/dev-notes/mem_profiler.md.           */

#pragma once
#include <stddef.h>

void mem_profiler_init(const char *host_ip, unsigned short port);
void mem_profiler_checkpoint(const char *tag);
void *mp_malloc(size_t size);
void *mp_calloc(size_t count, size_t size);
void *mp_realloc(void *ptr, size_t size);
void mp_free(void *ptr);

