/* Auto-generated by psvita-toolkit -- instrumented heap allocator wrappers. */
/* This toolkit has no ELF loader/relocator of its own, so it can't hook the  */
/* game .so's malloc/free calls automatically (same limitation documented in  */
/* so_patcher.py). Register mp_malloc/mp_calloc/mp_realloc/mp_free below in    */
/* place of the real malloc/calloc/realloc/free entries in your soloader's own */
/* libc import-resolution table. See docs/dev-notes/mem_profiler.md.           */

#include "mem_profiler_hooks.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

static int s_sock = -1;
static struct sockaddr_in s_dest;

void mem_profiler_init(const char *host_ip, unsigned short port) {
    s_sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (s_sock < 0) return;
    memset(&s_dest, 0, sizeof(s_dest));
    s_dest.sin_family = AF_INET;
    s_dest.sin_port = htons(port);
    inet_pton(AF_INET, host_ip, &s_dest.sin_addr);
}

static void mp_send(const char *event, void *ptr, size_t size, const char *tag) {
    if (s_sock < 0) return; /* mem_profiler_init() not called -- wrappers still work, just silent */
    char line[160];
    snprintf(line, sizeof(line), "%s,%p,%zu,%s", event, ptr, size, tag ? tag : "");
    sendto(s_sock, line, strlen(line), 0, (struct sockaddr *)&s_dest, sizeof(s_dest));
}

void mem_profiler_checkpoint(const char *tag) {
    mp_send("CHECKPOINT", NULL, 0, tag);
}

void *mp_malloc(size_t size) {
    void *p = malloc(size);
    if (p) mp_send("ALLOC", p, size, NULL);
    return p;
}

void *mp_calloc(size_t count, size_t size) {
    void *p = calloc(count, size);
    if (p) mp_send("ALLOC", p, count * size, NULL);
    return p;
}

void *mp_realloc(void *ptr, size_t size) {
    if (ptr) mp_send("FREE", ptr, 0, NULL);
    void *p = realloc(ptr, size);
    if (p) mp_send("ALLOC", p, size, NULL);
    return p;
}

void mp_free(void *ptr) {
    if (ptr) mp_send("FREE", ptr, 0, NULL);
    free(ptr);
}

