/* Auto-generated by psvita-toolkit -- soak-test heartbeat + optional random input. */
/* monkey_test_heartbeat() is always safe to call every frame/tick.            */
/* monkey_test_poll_input() is an OPTIONAL example: call it INSTEAD of         */
/* sceCtrlPeekBufferPositive() only behind your own build flag, and only for   */
/* unattended soak-test builds -- never in a build you'd ship.                 */
/* See docs/dev-notes/monkey_tester.md.                                        */

#pragma once
#include <psp2/ctrl.h>

void monkey_test_init(const char *host_ip, unsigned short port);
void monkey_test_heartbeat(void);
void monkey_test_poll_input(SceCtrlData *pad); /* optional, see header comment above */

