/* Auto-generated by psvita-toolkit -- soak-test heartbeat + optional random input. */
/* monkey_test_heartbeat() is always safe to call every frame/tick.            */
/* monkey_test_poll_input() is an OPTIONAL example: call it INSTEAD of         */
/* sceCtrlPeekBufferPositive() only behind your own build flag, and only for   */
/* unattended soak-test builds -- never in a build you'd ship.                 */
/* See docs/dev-notes/monkey_tester.md.                                        */

#include "monkey_test_hooks.h"
#include <psp2/kernel/processmgr.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

static int s_sock = -1;
static struct sockaddr_in s_dest;
static unsigned int s_tick = 0;

void monkey_test_init(const char *host_ip, unsigned short port) {
    s_sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (s_sock < 0) return;
    memset(&s_dest, 0, sizeof(s_dest));
    s_dest.sin_family = AF_INET;
    s_dest.sin_port = htons(port);
    inet_pton(AF_INET, host_ip, &s_dest.sin_addr);
    srand((unsigned int)sceKernelGetProcessTimeWide());
}

/* Sent roughly once a second at 60 ticks/s -- adjust the modulo if your loop rate differs. */
void monkey_test_heartbeat(void) {
    s_tick++;
    if (s_sock < 0 || (s_tick % 60) != 0) return;
    char line[32];
    snprintf(line, sizeof(line), "HEARTBEAT,%u", s_tick);
    sendto(s_sock, line, strlen(line), 0, (struct sockaddr *)&s_dest, sizeof(s_dest));
}

/* Example only: presses a random subset of buttons for a few ticks, then releases.
 * Adapt the button set / hold duration to what your game's menus/gameplay actually
 * expect -- this can't know what's "reasonable" input for your specific game. */
void monkey_test_poll_input(SceCtrlData *pad) {
    memset(pad, 0, sizeof(*pad));
    static const unsigned int buttons[] = {
        SCE_CTRL_UP, SCE_CTRL_DOWN, SCE_CTRL_LEFT, SCE_CTRL_RIGHT,
        SCE_CTRL_CROSS, SCE_CTRL_CIRCLE, SCE_CTRL_SQUARE, SCE_CTRL_TRIANGLE,
    };
    if ((rand() % 100) < 60) { /* ~60% of ticks: hold one random button */
        pad->buttons = buttons[rand() % (sizeof(buttons) / sizeof(buttons[0]))];
    }
    pad->lx = pad->ly = pad->rx = pad->ry = 128; /* sticks centered -- adjust if you want stick fuzzing too */
}

